In [40]:
import numpy as np
import pandas as pd

In [31]:
np.random.seed(55)
a=np.random.randint(30,99,(8,8))
a

array([[56, 69, 59, 91, 85, 67, 63, 84],
       [65, 76, 91, 42, 54, 61, 81, 30],
       [85, 92, 73, 79, 78, 40, 90, 89],
       [89, 74, 82, 51, 92, 82, 88, 91],
       [63, 75, 54, 48, 85, 57, 92, 48],
       [92, 86, 72, 97, 88, 37, 48, 95],
       [49, 49, 32, 62, 65, 63, 89, 51],
       [50, 33, 37, 50, 43, 46, 70, 44]], dtype=int32)

In [33]:
a[2,2]

np.int32(73)

array[row_start : row_end : row_step , col_start : col_end : col_step]

In [38]:
a[1:4,1:6]

array([[76, 91, 42, 54, 61],
       [92, 73, 79, 78, 40],
       [74, 82, 51, 92, 82]], dtype=int32)

In [64]:
k=np.random.randint(20,99,20)
k

array([68, 39, 94, 81, 20, 44, 68, 81, 43, 93, 56, 66, 53, 96, 63, 43, 94,
       28, 93, 49], dtype=int32)

In [78]:
pd.Series(k,)

0     68
1     39
2     94
3     81
4     20
5     44
6     68
7     81
8     43
9     93
10    56
11    66
12    53
13    96
14    63
15    43
16    94
17    28
18    93
19    49
dtype: int32

In [102]:
np.random.seed(55)
g=np.random.randint(20,99,(20,3))
pd.DataFrame(g)

0   1   2
0   97  46  59
1   92  49  81
2   75  57  53
3   74  55  66
4   81  97  32
5   44  91  51
6   92  71  94
7   20  75  82
8   63  69  68
9   98  30  80
10  79  79  64
11  72  41  97
12  82  72  78
13  81  53  65
14  44  38  75
15  47  82  38
16  82  76  62
17  94  87  78
18  27  38  85
19  39  39  94

In [104]:
df=pd.DataFrame(g,columns=['roll','age','adds',])

In [106]:
df

roll  age  adds
0     97   46    59
1     92   49    81
2     75   57    53
3     74   55    66
4     81   97    32
5     44   91    51
6     92   71    94
7     20   75    82
8     63   69    68
9     98   30    80
10    79   79    64
11    72   41    97
12    82   72    78
13    81   53    65
14    44   38    75
15    47   82    38
16    82   76    62
17    94   87    78
18    27   38    85
19    39   39    94

In [108]:
df.columns

Index(['roll', 'age', 'adds'], dtype='object')

In [110]:
df.age

0     46
1     49
2     57
3     55
4     97
5     91
6     71
7     75
8     69
9     30
10    79
11    41
12    72
13    53
14    38
15    82
16    76
17    87
18    38
19    39
Name: age, dtype: int32

In [112]:
df['age'].mean()

np.float64(62.25)

In [114]:
df['age'].median()

np.float64(63.0)

In [116]:
df['age'].mode()

0    38
Name: age, dtype: int32

In [118]:
df['age'].var()

np.float64(405.25)

In [120]:
df['age'].std()

np.float64(20.130822139197395)

In [122]:
df['age'].min()

np.int32(30)

In [124]:
df['age'].max()

np.int32(97)

In [126]:
df['age'].quantile(0.75)

np.float64(76.75)